rental/urls.py
from django.urls import path



from . import views
from .forms import NewRentalPropertyForm, NewContractForm
#from rental.views import FormWizardView

#orms = [NewRentalPropertyForm, NewContractForm]
app_name = 'rental'


app_name = 'rental'

urlpatterns = [
    path('', views.HomeView.as_view(), name="home" ),
    path('<int:pk>/',views.DetailView.as_view(), name='detail'),
    #path('new_rental/<int:pk>', FormWizardView.as_view(forms), name='new_rental'),
    path('new_rental/<int:pk>', views.new_rental, name='new_rental'),
    path('new_contract/<int:pk>', views.new_contract, name='new_contract'),
    path('update/<int:pk>', views.UpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.DeleteView.as_view(), name='delete'),
] 

trial/urls.py
from django.conf import settings 
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include, path


    
urlpatterns = [
        path('rental/', include('rental.urls')),
        path('admin/', admin.site.urls),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rental/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _
from model_utils import Choices
from PIL import Image
# Create your models here.

UserModel = get_user_model()

class Landlord(models.Model):
    user = models.OneToOneField(UserModel, on_delete=models.CASCADE)
    address = models.CharField(max_length=255)
    
    def __str__(self):
        return str(self.address)


class RentalProperty(models.Model):
    landlord = models.ForeignKey("Landlord", related_name='rentalpropertys', on_delete=models.CASCADE)
    created_by = models.ForeignKey(UserModel, related_name='rentalpropertys', on_delete=models.CASCADE)
    title = models.TextField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    PROPERTY_LISTING_CHOICES = Choices(
        ('APARTMENT', _('Apartment')),
        ('HOLIDAY_HOME', _('Holiday home')),
        ('SINGLE_FAMILY_HOME', _('Single family home')),
        ('COMMERCIAL', _('Commercial')),
    )
    type_of_property_listing = models.CharField(
        max_length = 50,
        choices = PROPERTY_LISTING_CHOICES,
        default = PROPERTY_LISTING_CHOICES.APARTMENT,)

    street = models.CharField(max_length=255)
    borough = models.CharField(max_length=255)
    image = models.ImageField(upload_to='images/', null=True, blank=True,)

    def __str__(self):
        return str(self.title)

class Contract(models.Model):
    rentalproperty = models.ForeignKey("RentalProperty", related_name='contracts', on_delete=models.CASCADE)
    insurance_required = models.BooleanField(default=True)
    other_terms = models.TextField(blank=True)

    def __str__(self):
        return str(self.insurance_required)

rental/forms.py
from django import forms
from .models import Landlord, RentalProperty, Contract

class NewLandlordForm(forms.ModelForm):
    class Meta:
        model = Landlord
        fields = ['address']


class NewRentalPropertyForm(forms.ModelForm):
    class Meta:
        model = RentalProperty
        fields = ['landlord','created_by','title','type_of_property_listing', 'street', 'borough', 'image']

class NewContractForm(forms.ModelForm):
    class Meta:
        model = Contract
        fields = ['insurance_required', 'other_terms']

rental/views.py
import os
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic 
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from formtools.wizard.views import SessionWizardView
from django.contrib import messages
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponseRedirect, HttpResponse

from django.forms.models import construct_instance
# Create your views here.
from .models import Landlord, RentalProperty, Contract
from .forms import NewRentalPropertyForm, NewContractForm

UserModel = get_user_model()

class HomeView(generic.ListView):
    model = RentalProperty
    template_name = 'rental/index.html'

    #def get_queryset(self):
        #query = super().get_queryset()
        #return Landlord.objects.filter(rentalproperty__created_by=self.request.user)

class DetailView(generic.DetailView):
    model = RentalProperty
    template_name = 'rental/detail.html'
    context_object_name = 'property'

    #def get_context_data(self, **kwargs):
        #context = super().get_context_data(**kwargs)
        #context['landlord']= Landlord.objects.all()
        #context['contract']= Contract.objects.all()
        #return context


def new_rental(request, pk):
    rentalproperty = get_object_or_404(RentalProperty, pk=pk)
    user = UserModel.objects.first()
    if request.method == 'POST':
        form = NewRentalPropertyForm(request.POST, request.FILES)
        #contract_form = NewContractForm(request.POST, prefix = "contracts")
        if form.is_valid():
            print ("all validation passed")
            rentalproperty = form.save()
            #contract_form.cleaned_data["rentalproperty"] = rentalproperty
            #contract.rentalproperty = rentalproperty
            #contract = contract_form.save()
            return HttpResponseRedirect(reverse("rental:new_contract"))
        else:
            messages.error(request, "Error")
            
    else: 
        form = NewRentalPropertyForm()
        #contract_form = NewContractForm(prefix = "contracts")
    return render(request, 'rental/new_rental.html', {
        'rentalproperty': rentalproperty,
        'form': form,
        #'contract_form': contract_form,
        })

def new_contract(request, pk):
    rentalproperty = get_object_or_404(RentalProperty, pk=pk)
    if request.method == 'POST':
        form = NewContractForm(request.POST)
        if form.is_valid():
            contract = form.save(commit=False)
            contract.rentalproperty = rentalproperty
            contract.save()
            return HttpResponseRedirect(reverse("rental:home"))
        else:
            messages.error(request, "Error")
            
    else:
        form = NewContractForm()
    return render(request, 'rental/new_contract.html', {
        'rentalproperty': rentalproperty,
        'form': form,
        })

class UpdateView(generic.UpdateView):
    model = RentalProperty
    form_class = NewRentalPropertyForm
    template_name = 'new_rental.html'
    success_url = reverse_lazy('rental:home')

class DeleteView(generic.DeleteView):
    model = RentalProperty
    success_url = reverse_lazy('rental:home')

rental/templates/rental/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detail View</title>
</head>
<body>
    
    <h1>This is the detail view</h1>
    <h3>From landlord</h3>
    <p>Landlord: {{property.created_by}}</p>
    <p>address: {{property.landlord.address}}</p>
    
    <h3>From Rental property</h3>
    <ul>
        <li>Title: {{property.title}}</li>
        {% if property.image %}
        <img src="{{property.image.url}}" height="200" alt=""/>
        {% endif %}
        <li>created at: {{property.created_at}}</li>
        <li>Type of property: {{property.type_of_property_listing}}</li>
        <li>Street: {{property.street}}</li>
        <li>Borough: {{property.borough}}</li>
        
        </ul>
      
        <ul>
        {% for data in property.contracts.all %}
        <li> insurance : {{data.insurance_required}}</li>
        <li> other terms: {{data.other_terms}}</li>
        {% endfor %}
        </ul>
    
</body>
</html>

rental/templates/rental/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Home Page</title>
</head>
<body>
    <div class="container">
    <h1>Welcome to our homepage</h1>
   
    <a href="{% url 'rental:new_rental' pk=1 %}">Create new rental</a>
    </div>
   <div class="container">
    <table class="table">
        <thead class="thead-inverse">
          <tr>
            <th>My apartment listing</th>
            <th></th>
            <th></th>
            <th>Created at</th>
          </tr>
        </thead>
        {% if rentalproperty_list %}
        <tbody>
            {% for propertys in rentalproperty_list %}
          <tr>
            <td>
            <a href="{% url 'rental:detail' propertys.pk %}">{{propertys.title}}</a>
              <small class="text-muted d-block">{{ board.description }}</small>
            </td>
            <td class="align-middle">
            <a href="{% url 'rental:delete' propertys.pk %}">delete</a>
            </td>
            <td class="align-middle">
            <a href="{% url 'rental:update' propertys.pk %}">update</a>
            </td>
            <td class="align-middle">
                {{ propertys.created_at }}
            </td>
          </tr>
          {% endfor %}
        </tbody>
        {%else %}
    <p>No rental title available</p>
    {% endif %}
      </table>
    </div>
</body>
</html>

rental/templates/rental/new_contract.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Contract</title>
</head>
<body>
    <H1>New rental</H1>
    <form method="POST">
        {% csrf_token %}
       {{ form.as_p }} 
        <input type="submit" value="submit">
    </form>
</body>
</html>

rental/templates/rental/new_rental.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New rental</title>
    <script>
      
    </script>
</head>
<body>
  <H1>New rental</H1>
    {% if rental_form.errors %}
    {% for field in rental_form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in rental_form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
    {% endif %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        
        <input type="submit" value="submit">
        <a href="/rental/new_contract/1">Next</a>
       
    </form>
    
</body>
</html>

rental/templates/rental/rentalproperty_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete</title>
</head>
<body>
    <h1>Delete?</h1>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="Delete">
        <a href="{% url 'rental:home' %}">Cancel</a>
    </form>
</body>
</html>